name: Build Android APK (Local)

on:
  push:
    branches:
      - main
    paths:
      - 'mobile/**'
  workflow_dispatch:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: mobile/package-lock.json

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install dependencies
        working-directory: mobile
        run: npm ci

      - name: Prebuild Android
        working-directory: mobile
        run: npx expo prebuild --platform android --clean

      - name: Build Android APK
        working-directory: mobile/android
        run: ./gradlew assembleRelease

      - name: Sign APK
        working-directory: mobile/android/app/build/outputs/apk/release
        env:
          KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
        run: |
          if [ -n "$KEYSTORE_BASE64" ]; then
            echo "Signing APK..."
            echo "$KEYSTORE_BASE64" | base64 -d > release.keystore
            $ANDROID_HOME/build-tools/33.0.0/apksigner sign \
              --ks release.keystore \
              --ks-key-alias "$KEY_ALIAS" \
              --ks-pass pass:"$KEYSTORE_PASSWORD" \
              --key-pass pass:"$KEY_PASSWORD" \
              --out app-release-signed.apk \
              app-release-unsigned.apk
            rm release.keystore
            echo "✅ APK signed successfully"
          else
            echo "⚠️  No signing keystore found - APK will be unsigned"
            echo "To sign APKs, add the following secrets to GitHub:"
            echo "  - ANDROID_KEYSTORE_BASE64"
            echo "  - ANDROID_KEY_ALIAS"
            echo "  - ANDROID_KEYSTORE_PASSWORD"
            echo "  - ANDROID_KEY_PASSWORD"
          fi

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: bookstor-android-${{ github.sha }}
          path: mobile/android/app/build/outputs/apk/release/*.apk
          retention-days: 30

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: mobile/android/app/build/outputs/apk/release/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

