name: Build Android APK

on:
  push:
    branches:
      - main
    paths:
      - 'mobile/**'
  workflow_dispatch:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: mobile/package-lock.json

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Expo and EAS
        run: |
          npm install -g eas-cli

      - name: Install dependencies
        working-directory: mobile
        run: npm ci

      - name: Setup Expo
        working-directory: mobile
        run: npx expo install

      - name: Build APK with EAS
        working-directory: mobile
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: |
          eas build --platform android --profile preview --non-interactive --no-wait

      - name: Get build URL
        working-directory: mobile
        run: |
          echo "Build started! Check your EAS dashboard for progress:"
          echo "https://expo.dev/accounts/$(npx expo whoami)/projects/bookstor/builds"

